import {
  pgTable,
  serial,
  timestamp,
  varchar,
  boolean,
  date,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  surname: varchar('surname', { length: 255 }).notNull(),
  dob: date('dob').notNull(),
  street: varchar('street', { length: 255 }).notNull(),
  city: varchar('city', { length: 255 }).notNull(),
  house: varchar('house', { length: 255 }).notNull(),
  state: varchar('state', { length: 255 }).notNull(),
  apartment: varchar('apartment', { length: 255 }),
  zip: varchar('zip', { length: 255 }).notNull(),
  phone: varchar('phone', { length: 255 }).notNull(),
  gender: varchar('gender', { length: 50 }).notNull(),
  citizenship: varchar('citizenship', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  isVerified: boolean('is_verified').default(false).notNull(),
  verificationToken: varchar('verification_token', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
